---
title: 'Lecture 4: Basics of plotting in ggplot2 - tasks'
author: "Dr Nicolaas Puts and Dr Lucas França"
date: "24 October 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

 - For the dataset available in https://raw.githubusercontent.com/HeJasonL/BIG-TAC/main/TutorialData.csv.

1. Create a scatter plot showing Age vs. Gaba and colour it by group using a colour palette of your choice.

```{r}
library(tidyverse)

readr::read_csv(file = 'https://raw.githubusercontent.com/HeJasonL/BIG-TAC/main/TutorialData.csv') %>% 
  ggplot2::ggplot(aes(x = Age, y = GABA)) + 
    geom_point(aes(colour = Group)) + 
    scale_color_brewer(palette = "Paired")
```


2. Add a regression line to the plot.

```{r}
library(ggpmisc)

readr::read_csv(file = 'https://raw.githubusercontent.com/HeJasonL/BIG-TAC/main/TutorialData.csv') %>% 
  ggplot2::ggplot(aes(x = Age, y = GABA)) + 
    geom_point(aes(colour = Group)) + 
    stat_poly_line() +
    stat_poly_eq() +
    scale_color_brewer(palette = "Paired")
```


3. Create a publication-ready boxplot using variables and colour palette of your choice.

```{r}
library(ggforce)

readr::read_csv(file = 'https://raw.githubusercontent.com/HeJasonL/BIG-TAC/main/TutorialData.csv') %>% 
  ggplot(aes(y = GABA,
             x = Group)) +
  geom_boxplot(aes(color = Group, 
                   fill = Group), 
               width = 0.5, 
               alpha = 0.3, 
               outlier.shape = NA) + 
  ggforce::geom_sina(aes(fill = Group, 
                         colour = Group), 
                size = 3, 
                pch = 21, 
                alpha = 0.4, 
                maxwidth = .5) + 
  theme_bw() +
  xlab("Group") +
  ylab("GABA") +
  ggtitle("GABA by group") +
  theme(plot.title = element_text(hjust = 0.5), 
        text = element_text(size = 24), 
        legend.position = c(0.9,0.9), 
        legend.title = element_blank(), 
        legend.background = element_blank()) + 
  scale_fill_brewer(palette = 'Paired') +
  scale_color_brewer(palette = 'Paired')
```

