---
title: 'Lecture 5: Comparing groups - tasks'
author: "Dr Nicolaas Puts and Dr Lucas França"
date: "07 November 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(foreign)
```


1. Load the following dataset:

```{r}
urlfile <- 'https://raw.githubusercontent.com/HeJasonL/BIG-TAC/main/TutorialData.csv' #this loads a csv file called TutorialData and puts it into urlfile

data <- readr::read_csv(file = urlfile) 
```

2. Describe the following variables.

```{r}
summary(data)
```

```{r}
data %>% 
  ggplot(aes(x = Sensory1)) + 
    geom_histogram(aes(fill = Group), binwidth = 6) + 
    theme_bw()
```

3. Using the right test, test the hypothesis that ASD population features a reduced sensory score. 

```{r}
library(car)
leveneTest(Sensory1 ~ Group, data = data, center = mean)
```

```{r}
t.test(formula = Sensory1 ~ Group, data = data, var.equal = TRUE)
```

4. Using the right test, test whether there are between percentages of Sex per Group (ASD/TDC).

```{r}
library(gmodels)

CrossTable(data$Sex, data$Group,
           format=c("SPSS"),
           prop.r = FALSE,
           prop.t = FALSE,
           prop.chisq=FALSE)
```

```{r}
chisq.test(xtabs(formula = ~ Sex + Group, data = data))
```


5. Plot a box plot of GABA per Group.

```{r}
data %>% 
  ggplot(aes(y = GABA,
             x = Group)) +
  geom_boxplot(aes(color = Group, 
                   fill = Group), 
               width = 0.5, 
               alpha = 0.3, 
               outlier.shape = NA) + 
  theme_bw() +
  xlab("Group") +
  ylab("GABA") +
  ggtitle("GABA by group") +
  theme(plot.title = element_text(hjust = 0.5), 
        text = element_text(size = 24), 
        legend.position = c(0.9,0.9), 
        legend.title = element_blank(), 
        legend.background = element_blank()) + 
  scale_fill_brewer(palette = 'Paired') +
  scale_color_brewer(palette = 'Paired')
```

