---
title: 'Lecture 6: Advanced concepts in R - tasks'
author: "Dr Nicolaas Puts and Dr Lucas França"
date: "07 November 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(foreign)
library(paletteer)
```


1. Load the following dataset:

```{r}
urlfile <- 'https://raw.githubusercontent.com/HeJasonL/BIG-TAC/main/TutorialData.csv' #this loads a csv file called TutorialData and puts it into urlfile

data <- read.csv(urlfile) %>% 
  tibble::as_tibble()

data
```


2. Create a for loop and write strings with a sequence of even numbers.

```{r}
for (i in c(0,2,4,6,8,10)){
  
  print(paste0('My number is ', i))
}
```
```{r}
for (i in seq(0,20,2)){
  
  print(paste0('My number is ', i))
}
```


3. Create a function to obtain the 95% CI for GABA.

CI: Mean -/+ 1.96*SD/sqrt(N)

```{r}
get_CI <- function(vec){
  lowerBoud <- mean(vec, na.rm = TRUE) - 1.96*sd(vec, na.rm = TRUE)/sqrt(length(vec))
  upperBound <- mean(vec, na.rm = TRUE) + 1.96*sd(vec, na.rm = TRUE)/sqrt(length(vec))
  
  CI <- c(lowerBoud, upperBound)
  
  return(CI)
  
}

get_CI(data$GABA)
```


4. Create a boxplot for GABA (in each Group) with stats.

```{r}
data %>% 
  ggplot(aes(x = Group, 
             y = GABA)) + 
  geom_boxplot(aes(colour = Group, 
                   fill = Group), 
               width = 0.5, 
               alpha = 0.3, 
               outlier.shape = NA) + 
  ggforce::geom_sina(aes(fill = Group, 
                         colour = Group), 
                     size = 3, 
                     pch = 21, 
                     alpha = 0.9, 
                     maxwidth = 0.5) + 
  theme_bw() + 
  ggtitle("GABA by Group") + 
  scale_fill_paletteer_d("MetBrewer::Juarez") + 
  scale_colour_paletteer_d("MetBrewer::Juarez") + 
  ggpubr::stat_compare_means(method = "t.test")
```

